https://www.kaggle.com/datasets/imtkaggleteam/breast-cancer

In [ ]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from sklearn.datasets import load_breast_cancer
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import confusion_matrix, classification_report, accuracy_score

In [ ]:
# Загрузка данных
data = load_breast_cancer()
X = pd.DataFrame(data.data, columns=data.feature_names)
y = data.target
# 0: 'malignant' (злокачественная), 1: 'benign' (доброкачественная)

In [ ]:
X.head()

,mean radius,mean texture,mean perimeter,mean area,mean smoothness,mean compactness,mean concavity,mean concave points,mean symmetry,mean fractal dimension,...,worst radius,worst texture,worst perimeter,worst area,worst smoothness,worst compactness,worst concavity,worst concave points,worst symmetry,worst fractal dimension
0,17.99,10.38,122.80,1001.0,0.11840,0.27760,0.3001,0.14710,0.2419,0.07871,...,25.38,17.33,184.60,2019.0,0.1622,0.6656,0.7119,0.2654,0.4601,0.11890
1,20.57,17.77,132.90,1326.0,0.08474,0.07864,0.0869,0.07017,0.1812,0.05667,...,24.99,23.41,158.80,1956.0,0.1238,0.1866,0.2416,0.1860,0.2750,0.08902
2,19.69,21.25,130.00,1203.0,0.10960,0.15990,0.1974,0.12790,0.2069,0.05999,...,23.57,25.53,152.50,1709.0,0.1444,0.4245,0.4504,0.2430,0.3613,0.08758
3,11.42,20.38,77.58,386.1,0.14250,0.28390,0.2414,0.10520,0.2597,0.09744,...,14.91,26.50,98.87,567.7,0.2098,0.8663,0.6869,0.2575,0.6638,0.17300
4,20.29,14.34,135.10,1297.0,0.10030,0.13280,0.1980,0.10430,0.1809,0.05883,...,22.54,16.67,152.20,1575.0,0.1374,0.2050,0.4000,0.1625,0.2364,0.07678


In [ ]:
print(X.isnull().sum())

mean radius                0
mean texture               0
mean perimeter             0
mean area                  0
mean smoothness            0
mean compactness           0
mean concavity             0
mean concave points        0
mean symmetry              0
mean fractal dimension     0
radius error               0
texture error              0
perimeter error            0
area error                 0
smoothness error           0
compactness error          0
concavity error            0
concave points error       0
symmetry error             0
fractal dimension error    0
worst radius               0
worst texture              0
worst perimeter            0
worst area                 0
worst smoothness           0
worst compactness          0
worst concavity            0
worst concave points       0
worst symmetry             0
worst fractal dimension    0
dtype: int64


In [ ]:
# Трейн тест сплит
X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.25, random_state=42
)

In [ ]:
# Масштабирование признаков
scaler = StandardScaler()
X_train_scaled = scaler.fit_transform(X_train)
X_test_scaled = scaler.transform(X_test)

In [ ]:
# Инициализация и обучение модели
# C — параметр регуляризации (чем меньше, тем сильнее штраф за большие веса)
model = LogisticRegression(C=1.0, solver='lbfgs')
model.fit(X_train_scaled, y_train)

LogisticRegression()

In [ ]:
# Предсказание
y_pred = model.predict(X_test_scaled)

In [ ]:
# Оценка результатов
print(f"Общая точность (Accuracy): {accuracy_score(y_test, y_pred):.4f}")
print("\nДетальный отчет по метрикам:")
print(classification_report(y_test, y_pred, target_names=data.target_names))

Общая точность (Accuracy): 0.9790

Детальный отчет по метрикам:
              precision    recall  f1-score   support

   malignant       0.96      0.98      0.97        54
      benign       0.99      0.98      0.98        89

    accuracy                           0.98       143
   macro avg       0.98      0.98      0.98       143
weighted avg       0.98      0.98      0.98       143



In [ ]:
# Интерпретация: какие признаки важнее всего?
weights = pd.Series(model.coef_[0], index=data.feature_names)
top_weights = weights.sort_values(ascending=False).head(10)
print("\nТоп-10 признаков, влияющих на решение о доброкачественности:")
print(top_weights)

IndexError: index 1 is out of bounds for axis 0 with size 1

#2.

In [ ]:
import numpy as np
import pandas as pd
from sklearn.datasets import load_digits
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.preprocessing import StandardScaler
from sklearn.metrics import classification_report, confusion_matrix

In [ ]:
# Загружаем датасет с рукописными цифрами
digits = load_digits()
X = digits.data  # Матрица признаков (64 пикселя на каждое изображение 8x8)
y = digits.target

In [ ]:
# Превращаем задачу в бинарную:
# Пусть 1 — это цифра '3', а 0 — любая другая цифра
y_binary = (y == 3).astype(int)

print(f"Всего объектов: {len(X)}")
print(f"Всего цифр '3': {sum(y_binary)}")

Всего объектов: 1797
Всего цифр '3': 183


In [ ]:
# Трейн тест сплит
X_train, X_test, y_train, y_test = train_test_split(
    X, y_binary, test_size=0.3, random_state=42, stratify=y_binary
)

In [ ]:
# Линейным моделям необходимо масштабирование пикселей (от 0..16 к -1..1)
scaler = StandardScaler()
X_train_scaled = scaler.fit_transform(X_train)
X_test_scaled = scaler.transform(X_test)

In [ ]:
# Обучаем логистическую регрессию
# class_weight='balanced' важен, так как "пятерок" в 9 раз меньше, чем остальных цифр
model = LogisticRegression(class_weight='balanced', max_iter=1000)
model.fit(X_train_scaled, y_train)

LogisticRegression(class_weight='balanced', max_iter=1000)

In [ ]:
# Оценка
y_pred = model.predict(X_test_scaled)

print("Отчет о классификации:")
print(classification_report(y_test, y_pred, target_names=['Не 3', '3']))

Отчет о классификации:
              precision    recall  f1-score   support

        Не 3       0.99      0.98      0.98       485
           3       0.82      0.91      0.86        55

    accuracy                           0.97       540
   macro avg       0.90      0.94      0.92       540
weighted avg       0.97      0.97      0.97       540



In [ ]:
# 7. Посмотрим на веса (какие пиксели важнее всего для распознавания цифры 3)
# Мы можем восстановить форму 8x8 из весов модели
coef_image = model.coef_.reshape(8, 8)
print("\nМатрица весов (влияние пикселей):")
print(np.round(coef_image, 1))


Матрица весов (влияние пикселей):
[[ 0.   0.2 -0.7 -0.1  1.3 -0.3 -0.1  0. ]
 [-0.1 -0.3  1.1  0.1  0.5  0.7  1.3  0.2]
 [ 0.  -0.2 -1.6 -1.2  1.  -0.4 -0.1 -0.1]
 [ 0.  -0.1 -1.9  0.1  0.4 -2.  -2.2  0. ]
 [ 0.  -0.8 -0.8 -0.1  0.   0.  -0.2  0. ]
 [ 0.   0.3 -1.2 -2.8  0.5  1.1  1.2 -0.1]
 [ 0.  -0.1 -0.2 -0.5  0.3  0.1  0.7 -0.4]
 [ 0.  -0.3  0.4 -0.2  0.4 -0.1 -0.2 -0.5]]


# Задание
Поработать с датасетом breast cancer и используя лог. регрессию, l1, l2 регуляризации попытаться максимизировать recall для метки/класса malignant

In [10]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from sklearn.datasets import load_breast_cancer
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import recall_score
from sklearn.metrics import confusion_matrix, classification_report, accuracy_score

In [ ]:
"""
Постановка задачи - поиск лучшей модели для выявления рака груди.
1. Подготовка и масштабирование.
2. Перебор параметров с l1, l2. Алгоритмы liblinear, lbfgs.
"""


data = load_breast_cancer()
X = pd.DataFrame(data.data, columns=data.feature_names)
y = data.target

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=42)

In [12]:
scaler = StandardScaler()
X_train_scaled = scaler.fit_transform(X_train)
X_test_scaled = scaler.transform(X_test)

In [32]:
best_recall = 0 # здесь храним лучший рез.
best_params = {} # лучшие параметры
best_model = None # лучшая модель

C_values = [0.001, 0.01, 0.1, 1, 10, 100]
penalties = ['l1', 'l2'] # типы регуляризации
solvers_l1 = ['liblinear'] 
solvers_l2 = ['lbfgs'] 

for penalty in penalties:
    if penalty == 'l1':
        solvers = solvers_l1
    else:
        solvers = solvers_l2
    
    for solver in solvers:
        for C in C_values:
            model = LogisticRegression(penalty=penalty, C=C, solver=solver, class_weight='balanced') # class_weight для корректировки веса классов
            model.fit(X_train_scaled, y_train)
            
            y_pred = model.predict(X_test_scaled)
            recall = recall_score(y_test, y_pred, pos_label=0)
            
            print(f"penalty={penalty} \t solver={solver} \t C={C} \t recall={recall:.6f}")
        
            # ищем лучшую модель
            if recall > best_recall:
                best_recall = recall
                best_params = {'penalty': penalty, 'solver': solver, 'C': C}
                best_model = model

print(f"\nЛучшие параметры:: {best_params}")
print(f"Лучший recall: {best_recall:.4f}")

penalty=l1 	 solver=liblinear 	 C=0.001 	 recall=1.000000
penalty=l1 	 solver=liblinear 	 C=0.01 	 recall=0.952381
penalty=l1 	 solver=liblinear 	 C=0.1 	 recall=0.984127
penalty=l1 	 solver=liblinear 	 C=1 	 recall=0.984127
penalty=l1 	 solver=liblinear 	 C=10 	 recall=0.984127
penalty=l1 	 solver=liblinear 	 C=100 	 recall=0.984127
penalty=l2 	 solver=lbfgs 	 C=0.001 	 recall=0.904762
penalty=l2 	 solver=lbfgs 	 C=0.01 	 recall=0.984127
penalty=l2 	 solver=lbfgs 	 C=0.1 	 recall=0.984127
penalty=l2 	 solver=lbfgs 	 C=1 	 recall=0.984127
penalty=l2 	 solver=lbfgs 	 C=10 	 recall=0.984127
penalty=l2 	 solver=lbfgs 	 C=100 	 recall=0.984127

Лучшие параметры:: {'penalty': 'l1', 'solver': 'liblinear', 'C': 0.001}
Лучший recall: 1.0000
